<?xml version="1.0"?>
<!DOCTYPE Entries[<!ELEMENT Entries (Day*)>
<!ELEMENT Day (NewEntry*, Event*)>
<!ELEMENT NewEntry (StartTime, EndTime, NameOfTeam, NumberOfPeople, PersonInCharge, Telephone, ConfirmationDate, Guide, Notes)>
<!ELEMENT Event (Notes, RepeatDays, RepeatMonths, RepeatYears)>
<!ELEMENT StartTime (#PCDATA)>
<!ELEMENT EndTime (#PCDATA)>
<!ELEMENT NameOfTeam (#PCDATA)>
<!ELEMENT NumberOfPeople (#PCDATA)>
<!ELEMENT PersonInCharge (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT ConfirmationDate (#PCDATA)>
<!ELEMENT Guide (#PCDATA)>
<!ELEMENT Notes (#PCDATA)>
<!ELEMENT RepeatDays (#PCDATA)>
<!ELEMENT RepeatMonths (#PCDATA)>
<!ELEMENT RepeatYears (#PCDATA)>
<!ATTLIST Day id ID #REQUIRED>
<!ATTLIST Day officer CDATA #IMPLIED>
<!ATTLIST NewEntry id ID #REQUIRED>
<!ATTLIST Event id ID #REQUIRED>]>
<Entries>
  <Day id="_13.9.2017" officer="Οφφιψερ">
    <NewEntry id="_guide:393">
      <StartTime>09:00</StartTime>
      <EndTime>10:30</EndTime>
      <NameOfTeam>hj</NameOfTeam>
      <NumberOfPeople>56</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>lk,n</Guide>
      <Notes>
      </Notes>
    </NewEntry>
  </Day>
</Entries>