<?xml version="1.0"?>
<!DOCTYPE Entries[<!ELEMENT Entries (Day*)>
<!ELEMENT Day (NewEntry*, Event*)>
<!ELEMENT NewEntry (StartTime, EndTime, NameOfTeam, NumberOfPeople, PersonInCharge, Telephone, ConfirmationDate, Guide, Notes)>
<!ELEMENT Event (Notes, RepeatDays, RepeatMoths, RepeatYears)>
<!ELEMENT StartTime (#PCDATA)>
<!ELEMENT EndTime (#PCDATA)>
<!ELEMENT NameOfTeam (#PCDATA)>
<!ELEMENT NumberOfPeople (#PCDATA)>
<!ELEMENT PersonInCharge (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT ConfirmationDate (#PCDATA)>
<!ELEMENT Guide (#PCDATA)>
<!ELEMENT Notes (#PCDATA)>
<!ELEMENT RepeatDays (#PCDATA)>
<!ELEMENT RepeatMoths (#PCDATA)>
<!ELEMENT RepeatYears (#PCDATA)>
<!ATTLIST Day id ID #REQUIRED>
<!ATTLIST NewEntry id ID #REQUIRED>
<!ATTLIST Event id ID #REQUIRED>]>
<Entries>
  <Day id="_1.8.2017">
    <NewEntry id="_guide:0">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:1">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:2">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:0">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_2.8.2017">
    <NewEntry id="_guide:3">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:4">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:5">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:1">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_24.8.2017">
    <NewEntry id="_guide:6">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:7">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:8">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:2">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_5.8.2017">
    <NewEntry id="_guide:12">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:13">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:14">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:4">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_6.8.2017">
    <NewEntry id="_guide:15">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:16">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:17">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:5">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_7.8.2017">
    <NewEntry id="_guide:18">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:19">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:20">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:6">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_8.8.2017">
    <NewEntry id="_guide:21">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:22">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:23">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:7">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_9.8.2017">
    <NewEntry id="_guide:24">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:25">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:26">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:8">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_25.8.2017">
    <NewEntry id="_guide:27">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:28">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:29">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:9">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_11.8.2017">
    <NewEntry id="_guide:30">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:31">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:32">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:10">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_12.8.2017">
    <NewEntry id="_guide:33">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:34">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:35">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:11">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_13.8.2017">
    <NewEntry id="_guide:36">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:37">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:38">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:12">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_14.8.2017">
    <NewEntry id="_guide:39">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:40">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:41">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:13">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_15.8.2017">
    <NewEntry id="_guide:42">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:43">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:44">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:14">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_16.8.2017">
    <NewEntry id="_guide:45">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:46">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:47">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:14">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_26.8.2017">
    <NewEntry id="_guide:48">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:49">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:50">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:15">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_18.8.2017">
    <NewEntry id="_guide:51">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:52">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:53">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:16">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_19.8.2017">
    <NewEntry id="_guide:54">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:55">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:56">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:17">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_20.8.2017">
    <NewEntry id="_guide:57">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:58">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:59">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:18">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_21.8.2017">
    <NewEntry id="_guide:60">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:61">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:62">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:19">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_22.8.2017">
    <NewEntry id="_guide:63">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:64">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:65">
      <StartTime>11:00</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <Event id="_event:20">
      <Notes>test</Notes>
      <RepeatDays>0</RepeatDays>
      <RepeatMonths>0</RepeatMonths>
      <RepeatYears>0</RepeatYears>
    </Event>
  </Day>
  <Day id="_23.8.2017">
    <NewEntry id="_guide:66">
      <StartTime>9:00</StartTime>
      <EndTime>10:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>
    </NewEntry>
    <NewEntry id="_guide:67">
      <StartTime>10:00</StartTime>
      <EndTime>11:00</EndTime>
      <NameOfTeam>anasto</NameOfTeam>
      <NumberOfPeople>50</NumberOfPeople>
      <PersonInCharge>
      </PersonInCharge>
      <Telephone>
      </Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>tzanis</Guide>
      <Notes>
      </Notes>