<?xml version="1.0"?>
<!DOCTYPE Settings[
<!ELEMENT Settings (Option*, Timetable*, ColorGroup*, EventGroup*, AlarmGroup*)>
  <!ELEMENT Option (#PCDATA)>
  <!ELEMENT Timetable (#PCDATA)>  
  <!ELEMENT ColorGroup (#PCDATA)> 
  <!ELEMENT EventGroup (#PCDATA)> 
  <!ELEMENT AlarmGroup (#PCDATA)>  
  <!ATTLIST Option id ID #REQUIRED>
  <!ATTLIST Timetable id ID #REQUIRED>
  <!ATTLIST ColorGroup id ID #REQUIRED>
  <!ATTLIST EventGroup id ID #REQUIRED>
  <!ATTLIST EventGroup name CDATA #REQUIRED>
  <!ATTLIST AlarmGroup id ID #REQUIRED>
  <!ATTLIST AlarmGroup name CDATA #REQUIRED>
]>
<Settings>
  <Option id="FullScreen">0</Option>
  <Option id="Language">0</Option>
  <Option id="LastIdReset">7.1.2018</Option>
  <Option id="LastBackUp">1</Option>
  <Option id="OldDataThreshold">2</Option>
  <Option id="DataPath">C:/Users/stavros/Documents/GitHub/Calendar/Assets/Calendar Data</Option>
  <Option id="ExportPath">C:\Users\stavros\Desktop</Option>
  <Option id="ImportPath">
  </Option>
  <Option id="TicketPrice">3</Option>
  <Option id="ReducedTicketPrice">1.5</Option>
  <Option id="MinimumTourTime">40</Option>
  <Timetable id="Monday">0</Timetable>
  <Timetable id="Tuesday">09:00,10:30,12:00,13:30</Timetable>
  <Timetable id="Wednesday">09:00,10:30,12:00,13:30</Timetable>
  <Timetable id="Thursday">09:00,10:30,12:00,13:30</Timetable>
  <Timetable id="Friday">09:00,10:30,12:00,13:30</Timetable>
  <Timetable id="Saturday">10:30,12:00,13:30,15:00,16:30</Timetable>
  <Timetable id="Sunday">10:30,12:00,13:30,15:00,16:30</Timetable>
  <ColorGroup id="ColorGroup.7" name="normal">0.2323276,0.4925334,0.5661765</ColorGroup>
  <ColorGroup id="ColorGroup.16" name="abnormal">0.7377626,0.4335509,0.320424</ColorGroup>
  <ColorGroup id="ColorGroup.17" name="funky">0.7377626,0.320424,0.6503072</ColorGroup>
  <EventGroup id="EventGroup.0" name=""></EventGroup>
</Settings>