<?xml version="1.0"?>
<!DOCTYPE Entries[
<!ELEMENT Entries (Day*)>
<!ELEMENT Day (Event*, Alarm*)>
<!ELEMENT Event (Attribute*)>
<!ELEMENT Alarm (Attribute*)>
<!ELEMENT Attribute (#PCDATA)>
<!ATTLIST Day id ID #REQUIRED>
<!ATTLIST Day officer CDATA #IMPLIED>
<!ATTLIST Event id ID #REQUIRED>
<!ATTLIST Alarm id ID #REQUIRED>
<!ATTLIST Attribute class CDATA #REQUIRED>
]>
<Entries>
  <Day id="_19.12.2017">
    <Event id="_guide.0">
      <Attribute class ="StartTime">10:30</Attribute>
      <Attribute class ="EndTime">11:00</Attribute>
      <Attribute class ="NameOfTeam">sdfsdf</Attribute>
      <Attribute class ="NumberOfPeople"></Attribute>
      <Attribute class ="PersonInCharge"></Attribute>
      <Attribute class ="Telephone"></Attribute>
      <Attribute class ="ConfirmationDate"></Attribute>
      <Attribute class ="Guide"></Attribute>
      <Attribute class ="Notes"></Attribute>
    </Event>
  </Day>
</Entries>