<?xml version="1.0"?>
<!DOCTYPE Entries[<!ELEMENT Entries (Day*)>
<!ELEMENT Day (NewEntry*, Event*)>
<!ELEMENT NewEntry (StartTime, EndTime, NameOfTeam, NumberOfPeople, PersonInCharge, Telephone, ConfirmationDate, Guide, Notes)>
<!ELEMENT Event (Notes, RepeatDays, RepeatMonths, RepeatYears)>
<!ELEMENT StartTime (#PCDATA)>
<!ELEMENT EndTime (#PCDATA)>
<!ELEMENT NameOfTeam (#PCDATA)>
<!ELEMENT NumberOfPeople (#PCDATA)>
<!ELEMENT PersonInCharge (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT ConfirmationDate (#PCDATA)>
<!ELEMENT Guide (#PCDATA)>
<!ELEMENT Notes (#PCDATA)>
<!ELEMENT RepeatDays (#PCDATA)>
<!ELEMENT RepeatMonths (#PCDATA)>
<!ELEMENT RepeatYears (#PCDATA)>
<!ATTLIST Day id ID #REQUIRED>
<!ATTLIST Day officer CDATA #IMPLIED>
<!ATTLIST NewEntry id ID #REQUIRED>
<!ATTLIST Event id ID #REQUIRED>]>
<Entries>
  <Day id="_14.9.2017">
    <NewEntry id="_guide.50">
      <StartTime>10:30</StartTime>
      <EndTime>12:00</EndTime>
      <NameOfTeam>jkhk</NameOfTeam>
      <NumberOfPeople>jkhkj</NumberOfPeople>
      <PersonInCharge>jkhkj</PersonInCharge>
      <Telephone>kjhkj</Telephone>
      <ConfirmationDate>
      </ConfirmationDate>
      <Guide>
      </Guide>
      <Notes>
      </Notes>
    </NewEntry>
  </Day>
</Entries>